@startuml

hide circle
hide empty members
hide empty methods


participant Utilisateur
participant application as Serveur
participant serveur as s

activate Utilisateur
activate Serveur

Utilisateur -> Serveur : Connexion
Utilisateur <- Serveur : Demande création de compte
Utilisateur -> Serveur : Envoi nom
Utilisateur -> Serveur : Envoi prénom
Utilisateur -> Serveur : Envoi mot de passe
Utilisateur -> Serveur : Envoi numéro de téléphone
Utilisateur -> Serveur : Envoi email
Utilisateur -> Serveur : Envoi entreprise
Utilisateur <-- Serveur : Vérification si prénom déjà existant
Utilisateur <-- Serveur : Si oui, vérification si nom déjà existant
Utilisateur <-- Serveur : Vérification si mot de passe sécurisé
Utilisateur <-- Serveur : Création du compte
Utilisateur <- Serveur : Demande ajout de projets
Utilisateur -> Serveur : Envoi nom de projets
activate s

Serveur -> s : Envoi données utilisateur
s -> s : stockage données
s -> Serveur : Conirmation données utilisateur
Serveur -> Utilisateur : Confirmation données utilisateur
deactivate Utilisateur
deactivate Serveur
deactivate s

@enduml
