@startuml

hide circle
hide empty members
hide empty methods


participant ChefDeProjet as c
participant Application as App
participant Serveur as s

activate c
activate App

c -> App : Connexion

activate s
App -> s : Demande vérification de l'association mdp/login
App <-- s : Renvoie une réponse
deactivate s

c -> App : Demande création de compte
c <-- App : Demande la saisie des données
c -> App : Envoi nom
c -> App : Envoi prénom
c -> App : Envoi numéro de téléphone
c -> App : Envoi email
c -> App : Envoi entreprise

activate s
App -> s : Envoi les données saisies
s -> s : Stock les données
s --> App : Confirmation de la création du client
App -> c : Confirmation de la création du client
c <-- App : Demande si le client a des projets
c -> App : Si oui envoi nom de projets
s <- App : Envoi les données saisies
s -> s : Stock les données
s --> App : Confirmation du stockage
App -> c : Confirmation du stockage
deactivate c
deactivate App
deactivate s

@enduml
